### PR TITLE
Fix construction of CMS polyhedra with discontinuities

### LINKED ISSUE #2046: Fix and implement last couple of missing ORANGE shape conversions
#1167 didn't quite get everything.
- CMS, LHCb, and ALICE all use "cut tubes"
- CMS and ALICE both have polyhedra with `numsides="1"` and inner radii, which is different from what we originally thought
- CMS and ATLAS both use polyhedra with different lo/hi radii
- I forgot about hyperbolic tube (but it's not used in any of our geometry)

Example cut tube from CMS run 3:
```xml
    <cutTube aunit="deg" deltaphi="7.90680999999999" highX="0" highY="0" highZ="1" lowX="0.48599950039277" lowY="0.00835999140593325" lowZ="-0.873919101611625" lunit="mm" name="pixfwdInnerDiskZplus_PixelForwardInnerDiskOuterRing_seg_10x7f7110ba4900" rmax="117.35" rmin="114.85" startphi="87.03229" z="15.5"/>
```

Example numsides=1 polyhedra from CMS run 4:
```xml
    <polyhedra aunit="deg" deltaphi="20" lunit="mm" name="HEC10x7f1fffce6500" numsides="1" startphi="350">
      <zplane rmax="1866.5" rmin="1775" z="3242"/>
      <zplane rmax="1866.5" rmin="1775" z="3347.8"/>
      <zplane rmax="1927.4" rmin="1775" z="3347.8"/>
      <zplane rmax="1927.4" rmin="1775" z="3436.4"/>
      <zplane rmax="1927.4" rmin="1838.8" z="3436.4"/>
      <zplane rmax="1927.4" rmin="1838.8" z="3770.42"/>
      <zplane rmax="1987.89" rmin="1838.8" z="3816.02"/>
      <zplane rmax="2876.5" rmin="2770.7" z="4462.99"/>
      <zplane rmax="2876.5" rmin="2813.42" z="4493.47"/>
      <zplane rmax="2876.5" rmin="2813.42" z="5541"/>
    </polyhedra>
```

Example "different rmin/rmax" polyhedra:
```xml
    <polyhedra aunit="deg" deltaphi="360" lunit="mm" name="HGCalHEAbsorber110x7f1fff5a7880" numsides="36" startphi="355">
      <zplane rmax="1984.08417370622" rmin="348.6" z="-20.75"/>
      <zplane rmax="2036.42657691209" rmin="348.6" z="20.7400000000002"/>
      <zplane rmax="2036.42657691209" rmin="418.6" z="20.7400000000002"/>
      <zplane rmax="2036.43919257929" rmin="418.6" z="20.7499999999995"/>
    </polyhedra>
```

  - [x] Implement a `CutCylinder` intersect region and solid (should be trivial) and conversion
  - [x] Rewrite `SolidConverter::polyhedra` and PolyPrism so that it does't just truncate a fully formed prism (which won't work since the side angles may not add up to 360 degrees) but builds up an extruded polygon
  - [ ] Implement hyperbolic tube (solid but no azi truncation), **LOW PRIORITY**

### PR DESCRIPTION
**Pull request by elliottbiondo**
This MR enacts two changes to get the CMS polyhedra cases to pass:

1) `StackedExtrudedPolygon` is modified so that, when extruded along the polyline, polyline segments with zero length are simply skipped. This allows for the creation of shapes where the `r(z)` shape of a polyhedron is discontinuous.

2) In `ExtrudedPolygon` the tolerance passed to `filter_collinear_points` is changed from the `BumpCalculator` tolerance, which is both absolute and relative, to a pure absolute tolerance. In the CMS test, a 36-gon has some (probably 18) of its points filtered out because using `BumpCalculator` with its large size created a tolerance that was far too aggressive. Note that we are already using a pure absolute tolerance for `RevolvedPolygon`.

Additionally, `G4Polyhedra` allows for cases where, the inner radius is only sometimes zero, creating discontinuous hollow regions. I added support to SEP for cases that look like:

```
    __________
   |__________|
        __
       |__|
```

But not cases where the radius is zero on exactly one end, i.e. it comes to a point:

```
    __________
   |__________|
        _
       /_\
```

This latter cases is not actually much harder. For now I added a DBC to catch it. I can do it for this MR, but I kind of feel like we should see it the wild before bothering to implement.

### CODE REVIEW

File: src/orange/orangeinp/StackedExtrudedPolygon.cc [hunk 1]
```diff
@@ -93,14 +93,14 @@ StackedExtrudedPolygon::StackedExtrudedPolygon(std::string&& label,
...
+    // Validate that z coordinates are weakly increasing
     CELER_VALIDATE(std::adjacent_find(polyline_.begin(),
                                       polyline_.end(),
                                       [](auto const& a, auto const& b) {
-                                          return a[Z] >= b[Z];
+                                          return a[Z] > b[Z];
                                       })
                        == polyline_.end(),
-                   << "z coordinates must be strictly increasing");
+                   << "z coordinates must be weakly increasing");
```
Comment (sethrj) [inline src/orange/orangeinp/StackedExtrudedPolygon.cc]: Is that common nomenclature? I would just write "nondecreasing".

**Review by sethrj — APPROVED** [review]

File: src/orange/orangeinp/StackedExtrudedPolygon.cc (hunk 1 above)
Comment (elliottbiondo) [reply src/orange/orangeinp/StackedExtrudedPolygon.cc]: Yes "weakly" and "strictly" are regularly used terms for the monotonicity of functions, but I agree "nondescreasing"is more clear.

Comment (sethrj) [reply src/orange/orangeinp/StackedExtrudedPolygon.cc]: I've heard and used "strictly" before but not "weakly".

**Comment by elliottbiondo** [comment]
This is still draft until I 1) write a good SEP test, 2) figure out the other CMS issue

File: src/orange/orangeinp/StackedExtrudedPolygon.cc (hunk 1 above)
Comment (elliottbiondo) [reply src/orange/orangeinp/StackedExtrudedPolygon.cc]: FWIW:

"To avoid ambiguity, the terms weakly monotone, weakly increasing and weakly decreasing are often used to refer to non-strict monotonicity."

https://en.wikipedia.org/wiki/Monotonic_function

**Comment by elliottbiondo** [comment]
@sethrj RTR

File: src/orange/orangeinp/StackedExtrudedPolygon.cc (hunk 1 above)
Comment (sethrj) [reply src/orange/orangeinp/StackedExtrudedPolygon.cc]: Yeah I saw that, wasn't doubting you 😄

File: src/orange/orangeinp/IntersectRegion.cc [hunk 2]
```diff
@@ -666,13 +666,10 @@ ExtrudedPolygon::ExtrudedPolygon(ExtrudedPolygon::VecReal2 const& polygon,
...
 
-    // Store only non-collinear points
-    Real3 const extents{
-        x_range_[1] - x_range_[0], y_range_[1] - y_range_[0], 0};
-    real_type abs_tol = ::celeritas::detail::BumpCalculator(
-        Tolerance<>::from_default())(extents);
-
-    polygon_ = detail::filter_collinear_points(polygon, abs_tol);
+    // Store only non-collinear points. Use an absolute tolerance; otherwise,
+    // for example, an arbitrilarly large regular dodecagon becomes a hexagon
```
Comment (sethrj) [inline src/orange/orangeinp/IntersectRegion.cc]:
```suggestion
    // for example, an arbitrarily large regular dodecagon becomes a hexagon
```
guess codespell doesn't catch them all 😉

File: src/orange/orangeinp/StackedExtrudedPolygon.cc [hunk 3]
```diff
@@ -187,18 +187,30 @@ StackedExtrudedPolygon::make_stack(detail::VolumeBuilder& vb,
...
     {
-        // Create the ExtrudedPolygon for this segment
-        ExtrudedPolygon shape{polygon,
-                              {polyline_[i], scaling_[i]},
-                              {polyline_[i + 1], scaling_[i + 1]}};
-
-        // Build this segment with unique label
-        nodes[i] = build_intersect_region(
-            vb, label_, this->make_segment_ext(si, i), shape);
+        CELER_VALIDATE(soft_zero(scaling_[0]) == soft_zero(scaling_[1])
```
Comment (sethrj) [inline src/orange/orangeinp/StackedExtrudedPolygon.cc]: Should this be 
```suggestion
        CELER_VALIDATE(soft_zero(scaling_[i]) == soft_zero(scaling_[i + 1])
```

File: test/orange/g4org/SolidConverter.test.cc [hunk 4]
```diff
@@ -826,6 +826,25 @@ TEST_F(SolidConverterTest, polyhedra)
...
+        static double const rmax[] = {2, 2, 2, 2, 2, 2};
+        auto sqrt_two = real_type{constants::sqrt_two};
+
+        // Full diamond shape, no interior
+        this->build_and_test(
+            G4Polyhedra(
+                "polyhedra", 0 * deg, 360 * deg, 4, std::size(z), z, rmin, rmax),
+            R"json({"_type":"all","daughters":[{"_type":"stackedextrudedpolygon","polygon":[[1.0,0.0],[0.0,1.0],[-1.0,0.0],[0.0,-1.0]],"polyline":[[0.0,0.0,0.0],[0.0,0.0,0.10000000149011612],[0.0,0.0,0.10000000149011612],[0.0,0.0,0.20000000298023224],[0.0,0.0,0.20000000298023224],[0.0,0.0,0.30000001192092896]],"scaling":[0.2828427255153656,0.2828427255153656,0.2828427255153656,0.2828427255153656,0.2828427255153656,0.2828427255153656]},{"_type":"negated","daughter":{"_type":"stackedextrudedpolygon","polygon":[[1.0,0.0],[0.0,1.0],[-1.0,0.0],[0.0,-1.0]],"polyline":[[0.0,0.0,0.0],[0.0,0.0,0.10000000149011612],[0.0,0.0,0.10000000149011612],[0.0,0.0,0.20000000298023224],[0.0,0.0,0.20000000298023224],[0.0,0.0,0.30000001192092896]],"scaling":[0.1414213627576828,0.1414213627576828,0.0,0.0,0.1414213627576828,0.1414213627576828]},"label":""}],"label":"polyhedra"})json",
```
Comment (sethrj) [inline test/orange/g4org/SolidConverter.test.cc]: wait, why do the polylines only have 7 digits of precision? (Did you do this on a single precision build)?  Also I don't think `sqrt_two` is used, and if you're passing it as input to geant4 you should use `double`

**Review by sethrj — APPROVED** [review]
Small comments to check out, looks good otherwise!

File: test/orange/g4org/SolidConverter.test.cc (hunk 4 above)
Comment (elliottbiondo) [reply test/orange/g4org/SolidConverter.test.cc]: Oops, yeah, single precision build. Will fix all.

Comment (elliottbiondo) [reply test/orange/g4org/SolidConverter.test.cc]: Yes one sqrt_two isn't used. Another one is, and it's `real_type` because it's not going to Geant4.

Comment (elliottbiondo) [reply test/orange/g4org/SolidConverter.test.cc]: Hold on, what has 7 digits of precision? I just rebuilt with `double` and I am getting the same strings.

Comment (sethrj) [reply test/orange/g4org/SolidConverter.test.cc]: Your polyline z points are `0.10000000149011612`, `0.20000000298023224` , etc. when they should be numerically `0.1`, `0.2`, etc... that looks like 1 + epsilon_float to me... or am I missing something?

Comment (elliottbiondo) [reply test/orange/g4org/SolidConverter.test.cc]: Fixed. Though I rebuilt with float but apparently didn't
