### PR TITLE
Fix build errors from Geant4@10

### LINKED ISSUE #828: Compile error with G4 10.6.3
Celeritas no longer compiles with Geant4 10.6.3 as its using API function that were added in a later version. The following files failed to compile: 

```
FAILED: src/celeritas/CMakeFiles/celeritas_g4vg.dir/ext/g4vg/SolidConverter.cc.o 
/cvmfs/sft.cern.ch/lcg/releases/gcc/11.3.0-ad0f5/x86_64-centos7/bin/g++ -DG4LIB_BUILD_DLL -DVECCORE_ENABLE_CUDA -I/home/esseivaj/bld4/devel/celeritas/src -I/home/esseivaj/bld4/devel/celeritas/build/include -isystem /home/esseivaj/bld4/devel/spack/var/spack/environments/celeritas/.spack-env/view/include -isystem /opt/cuda/11.8.0/include -isystem /home/esseivaj/bld4/devel/spack/var/spack/environments/celeritas/.spack-env/view/include/Geant4 -isystem /home/esseivaj/bld4/devel/spack/opt/spack/linux-centos7-cascadelake/gcc-11.3.0/clhep-2.4.6.0-cxuvt2z7pmefdpbcr4jzgu2qkhd3xsxe/include -isystem /bld4/home/esseivaj/devel/spack/opt/spack/linux-centos7-cascadelake/gcc-11.3.0/zlib-1.2.13-yaqekz3x2qihs3digztjtq3eahggv6t4/include -isystem /bld4/home/esseivaj/devel/spack/opt/spack/linux-centos7-cascadelake/gcc-11.3.0/expat-2.5.0-gzduk2bfkxfqoxwkqs6fxkxqqi2fe2bq/include -isystem /bld4/home/esseivaj/devel/spack/opt/spack/linux-centos7-cascadelake/gcc-11.3.0/xerces-c-3.2.3-4yis4cphgpkcynfxir4346muuwnvgds3/include -Wall -Wextra -Wno-psabi -pedantic -pedantic-errors -g -fPIC -faligned-new -std=c++17 -MD -MT src/celeritas/CMakeFiles/celeritas_g4vg.dir/ext/g4vg/SolidConverter.cc.o -MF src/celeritas/CMakeFiles/celeritas_g4vg.dir/ext/g4vg/SolidConverter.cc.o.d -o src/celeritas/CMakeFiles/celeritas_g4vg.dir/ext/g4vg/SolidConverter.cc.o -c /home/esseivaj/bld4/devel/celeritas/src/celeritas/ext/g4vg/SolidConverter.cc
/home/esseivaj/bld4/devel/celeritas/src/celeritas/ext/g4vg/SolidConverter.cc: In member function 'vecgeom::cxx::VUnplacedVolume* celeritas::g4vg::SolidConverter::para(celeritas::g4vg::SolidConverter::arg_type)':
/home/esseivaj/bld4/devel/celeritas/src/celeritas/ext/g4vg/SolidConverter.cc:393:15: error: 'const class G4Para' has no member named 'GetTheta'
  393 |         solid.GetTheta(),
      |               ^~~~~~~~
/home/esseivaj/bld4/devel/celeritas/src/celeritas/ext/g4vg/SolidConverter.cc:394:15: error: 'const class G4Para' has no member named 'GetPhi'
  394 |         solid.GetPhi());
      |               ^~~~~~
/home/esseivaj/bld4/devel/celeritas/src/celeritas/ext/g4vg/SolidConverter.cc: In member function 'vecgeom::cxx::VUnplacedVolume* celeritas::g4vg::SolidConverter::trap(celeritas::g4vg::SolidConverter::arg_type)':
/home/esseivaj/bld4/devel/celeritas/src/celeritas/ext/g4vg/SolidConverter.cc:566:15: error: 'const class G4Trap' has no member named 'GetTheta'
  566 |         solid.GetTheta(),
      |               ^~~~~~~~
/home/esseivaj/bld4/devel/celeritas/src/celeritas/ext/g4vg/SolidConverter.cc:567:15: error: 'const class G4Trap' has no member named 'GetPhi'
  567 |         solid.GetPhi(),
      |               ^~~~~~
/home/esseivaj/bld4/devel/celeritas/src/celeritas/ext/g4vg/SolidConverter.cc:571:15: error: 'const class G4Trap' has no member named 'GetAlpha1'; did you mean 'GetTanAlpha1'?
  571 |         solid.GetAlpha1(),
      |               ^~~~~~~~~
      |               GetTanAlpha1
/home/esseivaj/bld4/devel/celeritas/src/celeritas/ext/g4vg/SolidConverter.cc:575:15: error: 'const class G4Trap' has no member named 'GetAlpha2'; did you mean 'GetTanAlpha2'?
  575 |         solid.GetAlpha2());
      |               ^~~~~~~~~
      |               GetTanAlpha2
FAILED: src/accel/CMakeFiles/accel_objects.dir/SetupOptionsMessenger.cc.o 
/cvmfs/sft.cern.ch/lcg/releases/gcc/11.3.0-ad0f5/x86_64-centos7/bin/g++ -DG4LIB_BUILD_DLL -DVECCORE_ENABLE_CUDA -I/home/esseivaj/bld4/devel/celeritas/src -I/home/esseivaj/bld4/devel/celeritas/build/include -isystem /home/esseivaj/bld4/devel/spack/var/spack/environments/celeritas/.spack-env/view/include -isystem /opt/cuda/11.8.0/include -isystem /home/esseivaj/bld4/devel/spack/var/spack/environments/celeritas/.spack-env/view/include/Geant4 -isystem /home/esseivaj/bld4/devel/spack/opt/spack/linux-centos7-cascadelake/gcc-11.3.0/clhep-2.4.6.0-cxuvt2z7pmefdpbcr4jzgu2qkhd3xsxe/include -isystem /bld4/home/esseivaj/devel/spack/opt/spack/linux-centos7-cascadelake/gcc-11.3.0/zlib-1.2.13-yaqekz3x2qihs3digztjtq3eahggv6t4/include -isystem /bld4/home/esseivaj/devel/spack/opt/spack/linux-centos7-cascadelake/gcc-11.3.0/expat-2.5.0-gzduk2bfkxfqoxwkqs6fxkxqqi2fe2bq/include -isystem /bld4/home/esseivaj/devel/spack/opt/spack/linux-centos7-cascadelake/gcc-11.3.0/xerces-c-3.2.3-4yis4cphgpkcynfxir4346muuwnvgds3/include -Wall -Wextra -Wno-psabi -pedantic -pedantic-errors -g -fPIC -faligned-new -std=c++17 -MD -MT src/accel/CMakeFiles/accel_objects.dir/SetupOptionsMessenger.cc.o -MF src/accel/CMakeFiles/accel_objects.dir/SetupOptionsMessenger.cc.o.d -o src/accel/CMakeFiles/accel_objects.dir/SetupOptionsMessenger.cc.o -c /home/esseivaj/bld4/devel/celeritas/src/accel/SetupOptionsMessenger.cc
/home/esseivaj/bld4/devel/celeritas/src/accel/SetupOptionsMessenger.cc: In static member function 'static long int celeritas::{anonymous}::UICommandTraits<T, typename std::enable_if<is_integral_v<T>, void>::type>::from_string(const G4String&)':
/home/esseivaj/bld4/devel/celeritas/src/accel/SetupOptionsMessenger.cc:57:29: error: 'ConvertToLongInt' is not a member of 'G4UIcommand'
   57 |         return G4UIcommand::ConvertToLongInt(v.c_str());
      |                             ^~~~~~~~~~~~~~~~
```

### PR DESCRIPTION
**Pull request by drbenmorgan**
As reported in #828, the latest `develop` has a few compilation errors against Geant4 10.6 due to missing accessors. These are worked around here through use of the `G4VERSION_NUMBER` macro and direct/intermediate implementations:

- Missing `G4UIcommand::ConvertToLongInt()` is fixed by directly using `std::istringstream` as in the Geant4 implementation available from 10.7.
- Missing `GetTheta()`, `GetPhi()` accessors in `G4Trap` and `G4Para` calculate these parameters as in Geant4 11.0, using `GetSymAxis()` to obtain the needed inputs.
- Missing `GetAlpha...()` accessors in `G4Trap` simply use the `GetTanAlpha...()` accessors and `std::atan`.

The use of the direct Geant4 accessors is retained if the version supports them. Both implementations have been tested against Geant4 11, and produce the same results. Compilation against 10.6 works, but a few tests still fail:

```
The following tests FAILED:
	 81 - celeritas/ext/GeantImporter:FourSteelSlabs* (Failed)
	 83 - celeritas/ext/GeantImporter:OneSteelSphere.* (Failed)
	 98 - celeritas/global/AlongStep:Em3AlongStepTest.nofluct_nomsc (Failed)
	100 - celeritas/global/AlongStep:Em3AlongStepTest.msc_nofluct_finegrid (Failed)
	111 - celeritas/global/Stepper:TestEm3MscNofluct.* (Failed)
	151 - celeritas/user/Diagnostic:TestEm3* (Failed)
```

These need more investigation but on first look appear due to small (but above tolerance) differences in imported data, which is perhaps not surprising. I didn't look at trying to address these here until the compilation error fixes are reviewed and merged.

### CODE REVIEW

File: src/accel/SetupOptionsMessenger.cc [hunk 1]
```diff
@@ -54,7 +55,15 @@ struct UICommandTraits<T, std::enable_if_t<std::is_integral_v<T>>>
     static std::string to_string(T v) { return std::to_string(v); }
     static long from_string(G4String const& v)
     {
+        // Conversion to long int introduced in Geant4 10.7.0
+#if G4VERSION_NUMBER < 1070
+        G4long vl;
+        std::istringstream is(v);
+        is >> vl;
+        return vl;
+#else
```
Comment (sethrj) [inline src/accel/SetupOptionsMessenger.cc]: For compiler preprocessing and regular program flow with if/else, I find it more readable to put the "usual case" first and then the "else" is the exceptional case (in this instance, for backward compatibility).

File: src/celeritas/ext/g4vg/SolidConverter.cc [hunk 2]
```diff
@@ -561,18 +581,41 @@ auto SolidConverter::torus(arg_type solid_base) -> result_type
...
+    G4ThreeVector const axis = solid.GetSymAxis();
+    double const tan_theta_cos_phi = axis.x() / axis.z();
+    double const tan_theta_sin_phi = axis.y() / axis.z();
+
+    // Calculation of theta, phi, alpha1, alpha2 using implementations as
+    // in Geant4 11
+    double const theta = std::atan2(tan_theta_sin_phi, tan_theta_cos_phi);
+    double const phi
+        = std::atan(std::sqrt(tan_theta_cos_phi * tan_theta_cos_phi
+                              + tan_theta_sin_phi * tan_theta_sin_phi));
```
Comment (sethrj) [inline src/celeritas/ext/g4vg/SolidConverter.cc]: Aside from the lack of scaling in this case, I think this is identical to the `para` above. Maybe it'd be worth making a helper function in the `namespace {` at the top of the file that returns a std::pair of theta/phi?

**Review by sethrj — APPROVED** [review]
Thanks so much for doing this! I have two small comments. I'll see about adding a Geant4@10.6 CI today.

**Review by sethrj — APPROVED** [review]

File: src/celeritas/ext/g4vg/SolidConverter.cc (hunk 2 above)
Comment (drbenmorgan) [reply src/celeritas/ext/g4vg/SolidConverter.cc]: I've refactored the whole calculation for both, as both are really unit vectors, or at least in the form `{A.tan(theta)cos(phi), A.tan(theta)sin(phi), A}` so the calculation the same irrespective of overall normalisation.
