### PR TITLE
Fix NaN/assertion when taking extremely small steps in a field

### LINKED ISSUE #618: Debug assertion failure: VecgeomTrackView.hh:463: `is_soft_unit_vector(newdir)`
#### Failure:
```json
    "failure": {
     "condition": "is_soft_unit_vector(newdir)",
     "file": "/home/alund/celeritas_project/celeritas/src/celeritas/ext/VecgeomTrackView.hh",
     "line": 463, 
     "type": "DebugError",
     "which": "precondition failed"
    }   
```
#### Regression problem:
simple-cms+field+msc-vecgeom-cpu

#### Diagnosis:
The step length is very small (in particular, relative to the magnitude of the position). The leads to the end-state position calculated in the field stepper being the same as the beginning-state position, a chord length of 0, and NaNs for the chord direction, which the field propagator attempts to set as the new direction.

#### Minimal failing test:
```diff
diff --git a/test/celeritas/field/FieldPropagator.test.cc b/test/celeritas/field/FieldPropagator.test.cc
index 7d3b7af8..6653edf0 100644
--- a/test/celeritas/field/FieldPropagator.test.cc
+++ b/test/celeritas/field/FieldPropagator.test.cc
@@ -466,6 +466,26 @@ TEST_F(TwoBoxTest, gamma_exit)
     }
 }
 
+TEST_F(TwoBoxTest, electron_super_small_step)
+{
+    auto particle = this->init_particle(
+        this->particle()->find(pdg::electron()), MevEnergy{2});
+    UniformZField field(1 * units::tesla);
+    FieldDriverOptions driver_options;
+    constexpr real_type delta = 1e-14;
+
+    {
+        auto geo = this->init_geo({90, 90, 90}, {1, 0, 0});
+
+        auto propagate = make_mag_field_propagator<DormandPrinceStepper>(
+            field, driver_options, particle, &geo);
+        auto result = propagate(delta);
+
+        EXPECT_DOUBLE_EQ(delta, result.distance);
+    }
+}
+
 // Electron takes small steps up to and from a boundary
 TEST_F(TwoBoxTest, electron_small_step)
 {
```

### PR DESCRIPTION
**Pull request by sethrj**
See #618 for a description of the problem. If the chord is super small, the starting direction (which is kept in sync with the field state momentum) will be very close to the expected chord direction. This holds even when the chord length is zero. Therefore *only* update the trial direction for nontrivial (i.e. greater than the driver's "minimum step") distances.

Fixes #618

### CODE REVIEW

File: src/celeritas/field/FieldPropagator.hh [hunk 1]
```diff
@@ -162,7 +162,11 @@ CELER_FUNCTION auto FieldPropagator<DriverT>::operator()(real_type step)
         // Do a detailed check boundary check from the start position toward
         // the substep end point. Travel to the end of the chord, plus a little
         // extra.
-        geo_.set_dir(chord.dir);
+        if (chord.length >= driver_.minimum_step())
```
Comment (whokion) [inline src/celeritas/field/FieldPropagator.hh:165]: Logically this is somewhat redundant as always `remaining > driver_.minimum_step()` and the chord.length should be nontrivial even though it may be smaller than driver_.minimum_step() unless the field gradient is very big.  Not sure why this extra protection helps (i.e, what is wrong if the final direction is very close to the original direction?)

File: src/celeritas/field/detail/FieldUtils.hh [hunk 2]
```diff
@@ -62,10 +62,9 @@ inline CELER_FUNCTION Chord make_chord(Real3 const& src, Real3 const& dst)
         result.dir[i] = dst[i] - src[i];
     }
     result.length = norm(result.dir);
-    const real_type norm = 1 / result.length;
     for (int i = 0; i < 3; ++i)
     {
-        result.dir[i] *= norm;
+        result.dir[i] /= result.length;
```
Comment (whokion) [inline src/celeritas/field/detail/FieldUtils.hh:67]: 1 div + 3 mult + 1 variable vs. 3 div : is the latter more performant?  Actually I like the more terse/minimal code here.

File: test/celeritas/field/FieldPropagator.test.cc [hunk 3]
```diff
@@ -466,6 +466,26 @@ TEST_F(TwoBoxTest, gamma_exit)
     }
 }
 
+TEST_F(TwoBoxTest, electron_super_small_step)
+{
+    auto particle = this->init_particle(
+        this->particle()->find(pdg::electron()), MevEnergy{2});
+    UniformZField field(1 * units::tesla);
+    FieldDriverOptions driver_options;
+    for (real_type delta : {1e-14, 1e-8, 1e-2, 0.1})
```
Comment (whokion) [inline test/celeritas/field/FieldPropagator.test.cc:475]: It seems that 1e-14 and 1-e8 are practically too small.

**Review by whokion — COMMENTED** [review]
In general, the proposed change may not be harmful, but seems to be too protective.  Does this really help to dealing with small steps near driver.min_step()?

File: test/celeritas/field/FieldPropagator.test.cc (hunk 3 above)
Comment (amandalund) [reply test/celeritas/field/FieldPropagator.test.cc:475]: We do see a fair number of these very small steps in the demo loop -- they seem to be mainly range-limited steps for charged particles with extremely low energies, but there are also some cases where the remaining MFP is super small, leading to an extremely small interaction length.

File: src/celeritas/field/detail/FieldUtils.hh (hunk 2 above)
Comment (sethrj) [reply src/celeritas/field/detail/FieldUtils.hh:67]: I saw this while cleaning up: it's extra code that's possibly a "premature optimization" that might even be a pessimization on GPU since it might require an extra 64-bit register...

File: src/celeritas/field/FieldPropagator.hh (hunk 1 above)
Comment (sethrj) [reply src/celeritas/field/FieldPropagator.hh:165]: Since `chord.length` is always less than or equal to `remaining`, it can *sometimes* be less than the driver minimum step (e.g. in a strong magnetic field/low particle energy where the remaining step is just *barely* greater than the driver minimum step).

Additionally, on the first run through the loop (as *always* happens with the failing cases) even the `remaining`  can be less than minimum step.

File: test/celeritas/field/FieldPropagator.test.cc (hunk 3 above)
Comment (sethrj) [reply test/celeritas/field/FieldPropagator.test.cc:475]: Yep. It's rare but it seems to happen, therefore we need to make sure it works. (Or we need an error recovery mechanism, but it's better to just fix it if we can.)

Comment (whokion) [reply test/celeritas/field/FieldPropagator.test.cc:475]: As long as the field propagation concerns, we should not apply the field integration for the case when the step length is below a certain threshold, currently minimum_step = 1.0e-5 * units::millimeter.  As it will die after a small step, which not affect any physics result.

Comment (sethrj) [reply test/celeritas/field/FieldPropagator.test.cc:475]: If below the threshold then, should we just do a linear trace? We still want to physically move the particle those small distances, and we need to do the boundary intersections even if the distance is small.

Comment (whokion) [reply test/celeritas/field/FieldPropagator.test.cc:475]: Exactly.  The primary purpose of the field integration is to evaluate the curvature of track (small directional change at the end of track with an extra very small step length does not practically affect anything and the linear propagator should be good enough).  Anyway, let's merge this for now once the ci test is passed, but we may revisit self-consistent criteria when the field or linear propagator are applied.

**Review by whokion — APPROVED** [review]
