### PR TITLE
Fix incorrect Urban MSC path length correction due to discontinuity in positron cross section

### LINKED ISSUE #615: Debug assertion failure: AlongStep.hh:129: `mfp > 0`
#### Failure:
```json
    "failure": {
     "condition": "mfp > 0",
     "file": "/home/alund/celeritas_project/celeritas/src/celeritas/global/alongstep/AlongStep.hh",
     "line": 129,
     "type": "DebugError",
     "which": "internal assertion failed"
    }
```
#### Regression problem:
cms2018+field+msc-vecgeom-cpu

#### Diagnosis:
The positron step is limited by the distance to boundary = 8.64658290263130985e-02 (with distance to interaction = 9.46711477923071754e-02). Since it's a geo-limited step, `UrbanMscScatter` recalculates the true path length, with length = 9.48569009850495776e-02, which is then clamped to the interaction length. Because the step length is equal to the interaction length, the mfp is reduced to zero, but the action is still boundary crossing.

### PR DESCRIPTION
**Pull request by amandalund**
Because of a discontinuity in the Urban MSC positron cross section at 10 MeV, when a positron has energy slightly larger than 10 MeV it's possible for the final transport mean free path to be _larger_ than the initial mfp and therefore for the `alpha` calculated in `UrbanMscStepLimit::calc_geom_path()` to be negative. Since `UrbanMscScatter::calc_true_path()` checked for `alpha < 0` (instead of `alpha == -1`, indicating a small true path length) when determining which geom path --> true path conversion to use, the true path for these positrons was calculated using the wrong transformation.

See full discussion in #615
Some overlap with #641 ;)
Closes #615

### CODE REVIEW

File: src/celeritas/em/data/UrbanMscData.hh [hunk 1]
```diff
@@ -66,6 +66,12 @@ struct UrbanMscParameters
     {
         return units::MevEnergy{1e-6};
     }
+
+    //! Use a small step approximation for the path length correction
+    static CELER_CONSTEXPR_FUNCTION real_type small_step_transformation()
+    {
+        return -1;
+    }
```
Comment (sethrj) [inline src/celeritas/em/data/UrbanMscData.hh:74]: Since this is a special sentinel value for `alpha`, I think this should go in the `MscStep` defined in `phys/Interaction`. You'll note there's actually a TODO I put in there about refactoring it to encapsulate that sentinel value 😅

**Review by sethrj — COMMENTED** [review]
One minor suggestion to discuss: if you disagree I'm happy to leave as-is. (I don't know if the other MSC scattering methods use the same cross section approximations as this one, therefore also needing the special treatment for alpha, or whether it's just UrbanMSC.)

File: src/celeritas/em/data/UrbanMscData.hh (hunk 1 above)
Comment (amandalund) [reply src/celeritas/em/data/UrbanMscData.hh:74]: Makes sense (and you're right, I do see at least one other msc model that uses alpha this way) -- I'll move it there.

**Review by sethrj — APPROVED** [review]
Nice test case and fix!

File: test/celeritas/global/AlongStep.test.cc [hunk 2]
```diff
@@ -175,6 +177,34 @@ TEST_F(Em3AlongStepTest, msc_nofluct)
     }
 }
 
+TEST_F(Em3AlongStepTest, msc_nofluct_finegrid)
```
Comment (sethrj) [inline test/celeritas/global/AlongStep.test.cc:180]: I realized this test needs new CMake code to activate it:
```diff
diff --git a/test/CMakeLists.txt b/test/CMakeLists.txt
index bd88a999..cde8b3a1 100644
--- a/test/CMakeLists.txt
+++ b/test/CMakeLists.txt
@@ -335,6 +335,7 @@ if(CELERITAS_USE_Geant4)
       "-Em3*"
       "Em3AlongStepTest.nofluct_nomsc"
       "Em3AlongStepTest.msc_nofluct"
+      "Em3AlongStepTest.msc_nofluct_finegrid"
       "Em3AlongStepTest.fluct_nomsc"
   )
 else()
```
so I'll add that in my "tracking cut" PR which does along-step stuff.

Comment (amandalund) [reply test/celeritas/global/AlongStep.test.cc:180]: Ah good catch, thanks!
